# this is a simple test device setup that's used to compile and test the examples
# esphome:
#   name: components_test
#   build_path: build/components_test
esphome:
  name: sump-test
  friendly_name: sump test

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  - platform: esphome
    password: !secret OTA_password

# Enable Home Assistant API
api:
  encryption:
    key: !secret hassio_API_key

logger:

external_components:
  - source:
      type: local
      path: components
    refresh: always
    components:
      - empty_switch

switch:
  - platform: empty_switch
    name: Empty switch